=== SDaniel626/XUE9MH_XMLGYAK/XUE9MH_1018/XML_Schema_XUE9MH.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Egyszerű típusok - FElépítés -->
    <xs:element name="Fesztival_XUE9MH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Fesztival" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="helyszin" type="xs:string"/>
                            <xs:element name="ev" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="Fesz_ID" type="fesztivalTipus"/>
                        <xs:attribute name="T_FK" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="Tulajdonos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="adoszam" type="xs:int"/>
                            <xs:element name="alapitas" type="xs:int"/>
                            <xs:element name="bevetel" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="T_ID" type="tulajdonosTipus"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Fellepo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="orszag" type="xs:string"/>
                            <xs:element name="dij" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="FEL_ID" type="fellepoTipus"/>
                        <xs:attribute name="Fesz_FK" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="Bar" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="ital" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="ceg" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="B_ID" type="barTipus"/>
                        <xs:attribute name="Fesz_FK" type="xs:string" />
                        <xs:attribute name="A_FK" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="Alkalmazott" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="fizetes" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="A_ID" type="alkalmazottTipus"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Resztvevo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="lakcim">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="telepules" type="xs:string"/>
                                        <xs:element name="utca" type="xs:string"/>
                                        <xs:element name="hazszam" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="diakigazolvany" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="R_ID" type="resztvevoTipus"/>
                        <xs:attribute name="Fesz_FK" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="Kozvelemeny" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kerdezo" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="K_ID" type="kozvelemenyTipus"/>
                        <xs:attribute name="NY_FK" type="xs:string"/>
                        <xs:attribute name="R_FK" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Nyelvtudas" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nyelv" type="xs:string"/>
                            <xs:element name="szint" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="NY_ID" type="nyelvtudasTipus"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>


        <!-- Sajat tipusok -->
        <xs:simpleType name="fesztivalTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="f[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="tulajdonosTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="t[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="fellepoTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="e[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="barTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="b[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="alkalmazottTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="a[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="resztvevoTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="r[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="nyelvtudasTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="ny[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="kozvelemenyTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="k[0-9]" />
            </xs:restriction>
        </xs:simpleType>


        <!-- Elsődleges Kulcsok -->
        <xs:key name="fesztival_kulcs">
            <xs:selector xpath="Fesztival"/>
            <xs:field xpath="@Fesz_ID"/>
        </xs:key>

        <xs:key name="tulajdonos_kulcs">
            <xs:selector xpath="Tulajdonos"/>
            <xs:field xpath="@T_ID"/>
        </xs:key>

        <xs:key name="fellepo_kulcs">
            <xs:selector xpath="Fellepo"/>
            <xs:field xpath="@FEL_ID"/>
        </xs:key>

        <xs:key name="bar_kulcs">
            <xs:selector xpath="Bar"/>
            <xs:field xpath="@B_ID"/>
        </xs:key>

        <xs:key name="alkalmazott_kulcs">
            <xs:selector xpath="Alkalmazott"/>
            <xs:field xpath="@A_ID"/>
        </xs:key>

        <xs:key name="resztvevo_kulcs">
            <xs:selector xpath="Resztvevo"/>
            <xs:field xpath="@R_ID"/>
        </xs:key>

        <xs:key name="kozvelemeny_kulcs">
            <xs:selector xpath="Kozvelemeny"/>
            <xs:field xpath="@K_ID"/>
        </xs:key>

        <xs:key name="nyelvtudas_kulcs">
            <xs:selector xpath="Nyelvtudas"/>
            <xs:field xpath="@NY_ID"/>
        </xs:key>


        <!-- Idegen Kulcsok -->
        <xs:keyref refer="tulajdonos_kulcs" name="fesztival_tulajdonos_idegen_kulcs">
            <xs:selector xpath="Fesztival" />
            <xs:field xpath="@T_FK" />
        </xs:keyref>
        
        <xs:keyref refer="fesztival_kulcs" name="fesztival_felllepo_idegen_kulcs">
            <xs:selector xpath="Fellepo" />
            <xs:field xpath="@Fesz_FK" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="fesztival_bar_idegen_kulcs">
            <xs:selector xpath="Bar" />
            <xs:field xpath="@Fesz_FK" />
        </xs:keyref>

        <xs:keyref refer="alkalmazott_kulcs" name="bar_alkalmazott_idegen_kulcs">
            <xs:selector xpath="Bar" />
            <xs:field xpath="@A_FK" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="fesztival_resztvevo_idegen_kulcs">
            <xs:selector xpath="Resztvevo" />
            <xs:field xpath="@Fesz_FK" />
        </xs:keyref>

    </xs:element>
</xs:schema>

=== SDaniel626/XUE9MH_XMLGYAK/XUE9MH_1018/XML_XUE9MH.xml
<?xml version="1.0" encoding="utf-8"?>

<Fesztival_XUE9MH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema_XUE9MH.xsd">
	<Fesztival Fesz_ID="Fe01" T_FK="T01">
		<nev>Fyre</nev>
		<helyszin>Great Exuma</helyszin>
		<ev>2017</ev>
	</Fesztival>
	<Tulajdonos T_ID="T01">
		<nev>Billy McFarland</nev>
		<adoszam>12345678</adoszam>
		<alapitas>2015</alapitas>
		<bevetel>5200000</bevetel>
	</Tulajdonos>
	<Fellepo FEL_ID="F01" Fesz_FK="T01">
		<nev>Billie Elish</nev>
		<orszag>UK</orszag>
		<dij>3000000</dij>
	</Fellepo>
	<Fellepo FEL_ID="F02" Fesz_FK="T01">
		<nev>Eminem</nev>
		<orszag>USA</orszag>
		<dij>5000000</dij>
	</Fellepo>
	<Bar B_ID="B01" Fesz_FK="T01" A_FK="A01">
		<nev>Kek osztriga Bar</nev>
		<ital>Cosmo</ital>
		<ital>Redbull-Vodka</ital>
		<ceg>Red Bull</ceg>
	</Bar>
	<Bar B_ID="B01" Fesz_FK="T01" A_FK="A02">
		<nev>Roxy</nev>
		<ital>Vodka-narancs</ital>
		<ital>Mohito</ital>
		<ceg>Coka Cola</ceg>	
	</Bar>
	<Alkalmazott A_ID="A01">
		<nev>Nagy Andrea</nev>
		<muszak>Esti</muszak>
		<fizetes>350000</fizetes>
	</Alkalmazott>
	<Alkalmazott A_ID="A02">
		<nev>Nehez Peter</nev>
		<muszak>Delutan</muszak>
		<fizetes>275000</fizetes>
	</Alkalmazott>
	<Resztvevo R_ID="R01" Fesz_FK="F01">
		<nev>Tom Sawyer</nev>
		<lakcim>
			<telepules>Bristol</telepules>
			<utca>Darwin's street</utca>
			<hazszam>22</hazszam>
		</lakcim>
		<diakigazolvany>12345678</diakigazolvany>
	</Resztvevo>
	<Resztvevo R_ID="R02" Fesz_FK="F01">
		<nev>Vagany Kristof</nev>
		<lakcim>
			<telepules>Dunaszerdahely</telepules>
			<utca>Petofi utca</utca>
			<hazszam>3</hazszam>
		</lakcim>
		<diakigazolvany>87654321</diakigazolvany>
	</Resztvevo>
	<Resztvevo R_ID="R03" Fesz_FK="F01">
		<nev>Kovacs Alexandra</nev>
		<lakcim>
			<telepules>Budapest</telepules>
			<utca>Sereny utca</utca>
			<hazszam>12</hazszam>
		</lakcim>
		<diakigazolvany>45678123</diakigazolvany>
	</Resztvevo>
	<Kozvelemeny K_ID="K01" NY_FK="NY02" R_FK="R03">
		<kerdezo>Guid Trutko</kerdezo>
	</Kozvelemeny>
	<Nyelvtudas NY_ID="NY01">
		<nyelv>angol</nyelv>
		<szint>B</szint>
	</Nyelvtudas>
	<Nyelvtudas NY_ID="NY02">
		<nyelv>angol</nyelv>
		<szint>C</szint>
	</Nyelvtudas>
	<Nyelvtudas NY_ID="NY03">
		<nyelv>nemet</nyelv>
		<szint>B</szint>
	</Nyelvtudas>
</Fesztival_XUE9MH>
