=== SDaniel626/XUE9MH_XMLGYAK/XUE9MH_1004/XUE9MH_orarend.dtd
<!ELEMENT SD_orarend (ora+)>
<!ELEMENT ora (targy+,idopont+,helyszin+,oktato+,szak+)>
<!ATTLIST ora ID ID #REQUIRED>
<!ATTLIST ora tipus (EA | GYK) "EA">
<!ELEMENT idopont (nap,tol,ig)>
<!ELEMENT targy (#PCDATA)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>

=== SDaniel626/XUE9MH_XMLGYAK/XUE9MH_1108/Dom_Parse_XUE9MH/XUE9MH_orarend1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- <!DOCTYPE SD_orarend SYSTEM "XUE9MH_orarend.dtd"> --><SD_orarend>
     
    <!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XUE9MH_orarend.xsd">  -->
    
    <!-- <SD_orarend> -->
    	
    <ora ID="x01" tipus="EA">
        		
        <targy>Korszeru Informacios Technologiak</targy>
        		
        <idopont>
            			
            <nap>Kedd</nap>
            			
            <tol>8</tol>
            			
            <ig>10</ig>
            		
        </idopont>
        		
        <helyszin>Inf.103</helyszin>
        		
        <oktato>Árvai László Lajos</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x02" tipus="EA">
        		
        <targy>Adatkezeles XML-ben</targy>
        		
        <idopont>
            			
            <nap>Kedd</nap>
            			
            <tol>12</tol>
            			
            <ig>14</ig>
            		
        </idopont>
        		
        <helyszin>XXXII eloado</helyszin>
        		
        <oktato>Dr. Bendarik László</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x03" tipus="EA">
        		
        <targy>Webes alkalmazasok java</targy>
        		
        <idopont>
            			
            <nap>Kedd</nap>
            			
            <tol>14</tol>
            			
            <ig>16</ig>
            		
        </idopont>
        		
        <helyszin>online</helyszin>
        		
        <oktato>Viktor Selmeci</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x13" tipus="GYK">
        		
        <targy>Webes alkalmazasok java</targy>
        		
        <idopont>
            			
            <nap>Kedd</nap>
            			
            <tol>16</tol>
            			
            <ig>18</ig>
            		
        </idopont>
        		
        <helyszin>online</helyszin>
        		
        <oktato>Viktor Selmeci</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x04" tipus="EA">
        		
        <targy>Szamitogepes Halozatok</targy>
        		
        <idopont>
            			
            <nap>Szerda</nap>
            			
            <tol>8</tol>
            			
            <ig>10</ig>
            		
        </idopont>
        		
        <helyszin>II eloado</helyszin>
        		
        <oktato>Dr. Kovacs Szilveszter</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x12" tipus="GYK">
        		
        <targy>Adatkezeles XML-ben</targy>
        		
        <idopont>
            			
            <nap>Szerda</nap>
            			
            <tol>10</tol>
            			
            <ig>12</ig>
            		
        </idopont>
        		
        <helyszin>Inf. 101</helyszin>
        		
        <oktato>Dr. Bendarik László</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x14" tipus="GYK">
        		
        <targy>Szamitogepes Halozatok</targy>
        		
        <idopont>
            			
            <nap>Csutortok</nap>
            			
            <tol>12</tol>
            			
            <ig>14</ig>
            		
        </idopont>
        		
        <helyszin>III eloado</helyszin>
        		
        <oktato>Dr. Kovacs Szilveszter</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    	
    <ora ID="x11" tipus="GYK">
        		
        <targy>Korszeru Informacios Technologiak</targy>
        		
        <idopont>
            			
            <nap>Csutortok</nap>
            			
            <tol>16</tol>
            			
            <ig>18</ig>
            		
        </idopont>
        		
        <helyszin>Inf. 114</helyszin>
        		
        <oktato>Soós Róbert</oktato>
        		
        <szak>Mernök info.</szak>
        	
    </ora>
    
</SD_orarend>
