=== SDaniel626/XUE9MH_XMLGYAK/XMLTaskXUE9MH/1.feladat/XMLSchemaXUE9MH.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="Gyorsetterem" type="gyorsetteremType">
		<xs:key name="GyrosPK">
			<xs:selector xpath="Gyros" />
			<xs:field xpath="GyrosID" />
		</xs:key>
		<xs:key name="GyrososPK">
			<xs:selector xpath="Gyrosos" />
			<xs:field xpath="GyrososID" />
		</xs:key>
		<xs:key name="VasarloPK">
			<xs:selector xpath="Vasarlo" />
			<xs:field xpath="VasarloID" />
		</xs:key>
		<xs:key name="BeszallitoPK">
			<xs:selector xpath="Beszallito" />
			<xs:field xpath="BeszallitoID" />
		</xs:key>
		<xs:key name="KiszallitoPK">
			<xs:selector xpath="Kiszallito" />
			<xs:field xpath="KiszallitoID" />
		</xs:key>
		<xs:key name="BankkartyaPK">
			<xs:selector xpath="Bankkartya" />
			<xs:field xpath="Kartyaszam" />
		</xs:key>
		<xs:keyref refer="GyrososPK" name="GyrosGyartojaFK">
			<xs:selector xpath="Gyros" />
			<xs:field xpath="GyrososFK" />
		</xs:keyref>
		<xs:keyref refer="VasarloPK" name="BankkartyaTulajFK">
			<xs:selector xpath="Bankkartya" />
			<xs:field xpath="VasarloFK" />
		</xs:keyref>
		<xs:keyref refer="GyrososPK" name="kiszallitoGyrososFK">
			<xs:selector xpath="Kiszallito" />
			<xs:field xpath="GyrososFK" />
		</xs:keyref>
				<xs:keyref refer="GyrosPK" name="vasarloGyrosaFK">
			<xs:selector xpath="Rendel" />
			<xs:field xpath="GyrosFK" />
		</xs:keyref>
				<xs:keyref refer="VasarloPK" name="gyrosVasarloFK">
			<xs:selector xpath="Rendel" />
			<xs:field xpath="VasarloFK" />
		</xs:keyref>
		<xs:keyref refer="BeszallitoPK" name="gyrososBeszallitottolFK">
			<xs:selector xpath="Beszallit" />
			<xs:field xpath="BeszallitoFK" />
		</xs:keyref>
		<xs:keyref refer="GyrososPK" name="beszallitoGyrososnakFK">
			<xs:selector xpath="Beszallit" />
			<xs:field xpath="GyrososFK" />
		</xs:keyref>
	</xs:element>
	
	<xs:complexType name="gyorsetteremType">
		<xs:sequence>
			<xs:element name="Gyros" type="gyrosType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Gyrosos" type="gyrososType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Rendel" type="rendelType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Vasarlo" type="vasarloType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Beszallit" type="beszallitType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Beszallito" type="beszallitoType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Kiszallito" type="kiszallitoType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Bankkartya" type="bankkartyaType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="gyrosType">
		<xs:sequence>
			<xs:element name="GyrosID" type="xs:integer"/>
			<xs:element name="Suly" type="xs:integer"/>
			<xs:element name="Toltelek" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="GyrososFK" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="gyrososType">
		<xs:sequence>
			<xs:element name="GyrososID" type="xs:integer"/>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
			<xs:element name="Telefonszam" type="xs:string"/>
			<xs:element name="Nyitvatartas" type="nyitvatartasType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="nyitvatartasType">
		<xs:sequence>
			<xs:element name="Hetkoznap" type="xs:integer"/>
			<xs:element name="Hetvege_unnepek" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="rendelType">
		<xs:sequence>
			<xs:element name="GyrosFK" type="xs:integer"/>
			<xs:element name="VasarloFK" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="vasarloType">
		<xs:sequence>
			<xs:element name="VasarloID" type="xs:integer"/>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Telefonszam" type="xs:string"/>
			<xs:element name="Cim" type="cimType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="cimType">
		<xs:sequence>
			<xs:element name="Hazszam" type="xs:integer"/>
			<xs:element name="Utca" type="xs:string"/>
			<xs:element name="Varos" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="beszallitType">
		<xs:sequence>
			<xs:element name="GyrososFK" type="xs:integer"/>
			<xs:element name="BeszallitoFK" type="xs:integer"/>
			<xs:element name="Termek" type="xs:string"/>
			<xs:element name="Datum" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="beszallitoType">
		<xs:sequence>
			<xs:element name="BeszallitoID" type="xs:integer"/>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
			<xs:element name="Telefonszam" type="xs:string"/>
			<xs:element name="Cim" type="cimType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="kiszallitoType">
		<xs:sequence>
			<xs:element name="KiszallitoID" type="xs:integer"/>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
			<xs:element name="Telefonszam" type="xs:string"/>
			<xs:element name="GyrososFK" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="bankkartyaType">
		<xs:sequence>
			<xs:element name="Kartyaszam" type="xs:integer"/>
			<xs:element name="Bank" type="xs:string"/>
			<xs:element name="Tipus" type="xs:string"/>
			<xs:element name="Lejarati_datum" type="xs:string"/>
			<xs:element name="VasarloFK" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== SDaniel626/XUE9MH_XMLGYAK/XMLTaskXUE9MH/1.feladat/XML_XUE9MH.xml
<?xml version="1.0" encoding="UTF-8"?>

<Gyorsetterem xsi:noNamespaceSchemaLocation="XMLSchemaXUE9MH.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Gyros>
		<GyrosID>1</GyrosID>
		<Suly>250</Suly>
		<Toltelek>Minden_Csipos</Toltelek>
		<GyrososFK>1</GyrososFK>
	</Gyros>
	<Gyros>
		<GyrosID>2</GyrosID>
		<Suly>500</Suly>
		<Toltelek>Minden</Toltelek>
		<GyrososFK>1</GyrososFK>
	</Gyros>
	<Gyrosos>
		<GyrososID>1</GyrososID>
		<Nev>Hammas</Nev>
		<Email>hammas@hesbollah.allah</Email>
		<Telefonszam>0608449860</Telefonszam>
		<Nyitvatartas>
			<Hetkoznap>0820</Hetkoznap>
			<Hetvege_unnepek>1116</Hetvege_unnepek>
		</Nyitvatartas>
		<KiszallitoFK>1</KiszallitoFK>
	</Gyrosos>
	<Rendel>
		<GyrosFK>1</GyrosFK>
		<VasarloFK>1</VasarloFK>
	</Rendel>
	<Vasarlo>
		<VasarloID>1</VasarloID>
		<Nev>Simon Daniel</Nev>
		<Telefonszam>0905338642</Telefonszam>
		<Cim>
			<Hazszam>23</Hazszam>
			<Utca>Egyetem ut</Utca>
			<Varos>Miskolc</Varos>
		</Cim>
	</Vasarlo>
	<Beszallit>
		<GyrososFK>1</GyrososFK>
		<BeszallitoFK>1</BeszallitoFK>
		<Termek>Hus</Termek>
		<Datum>2021-12-23</Datum>
	</Beszallit>
	<Beszallito>
		<BeszallitoID>1</BeszallitoID>
		<Nev>Mucsen-ducsen</Nev>
		<Email>muchen@duchen.ak</Email>
		<Telefonszam>0756354789</Telefonszam>
		<Cim>
			<Hazszam>12</Hazszam>
			<Utca>Hajnal</Utca>
			<Varos>Debrecen</Varos>
		</Cim>
	</Beszallito>
	<Kiszallito>
		<KiszallitoID>1</KiszallitoID>
		<Nev>Nagy Sanyi</Nev>
		<Email>sanyi.nagy@gmail.com</Email>
		<Telefonszam>0514654254</Telefonszam>
		<GyrososFK>1</GyrososFK>
	</Kiszallito>
	<Bankkartya>
		<Kartyaszam>1234432112344321</Kartyaszam>
		<Bank>OTP</Bank>
		<Tipus>Visa</Tipus>
		<Lejarati_datum>11/21</Lejarati_datum>
		<VasarloFK>1</VasarloFK>
	</Bankkartya>
	<Bankkartya>
		<Kartyaszam>7456654774566547</Kartyaszam>
		<Bank>Erste</Bank>
		<Tipus>Master Card</Tipus>
		<Lejarati_datum>06/25</Lejarati_datum>
		<VasarloFK>1</VasarloFK>
	</Bankkartya>
</Gyorsetterem>
